[theme]
base = "light"
primaryColor = "#1A73E8"
backgroundColor = "#F8FAFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 50

[browser]
gatherUsageStats = false
